use_frameworks!

platform :ios, '10.0'

target 'GGXSynthesisSpeech_Example' do
  pod 'GGXSynthesisSpeech', :path => '../'

  target 'GGXSynthesisSpeech_Tests' do
    inherit! :search_paths

    
  end
end
